/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.view;

import edu.neu.csye6200.controller.ClassRoomController;
import edu.neu.csye6200.controller.GroupController;
import edu.neu.csye6200.controller.ImmunizationContorller;
import edu.neu.csye6200.controller.StudentController;
import edu.neu.csye6200.controller.TeacherController;
import edu.neu.csye6200.controller.Test;
import edu.neu.csye6200.model.Classroom;
import edu.neu.csye6200.model.Group;
import edu.neu.csye6200.model.Student;
import edu.neu.csye6200.model.Teacher;
import edu.neu.csye6200.model.Vaccine;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ke
 */
public class ApplicationMainJFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form ApplicationMainJFrame
     */
  
     private StudentController studentController = new StudentController();
     private List<Student> students = new ArrayList<>();
     private List<Teacher> teachers = new ArrayList<>();
     private List<Classroom>classrooms = new ArrayList<>();
     private List<Vaccine> vaccine = new ArrayList<>();
        private Vaccine immuMap;
        ImmunizationContorller immunizationContorller = new ImmunizationContorller();
        private Map<String,Integer> requiredVaccineMap = new HashMap<>();
    //CardLayout layout=(CardLayout)userProcessContainer.getLayout();
    public ApplicationMainJFrame() {
        initComponents();
        
    StudentController studentController = new StudentController();
    students = studentController.getList();
    
    ImmunizationContorller immunizationContorller = new ImmunizationContorller();
    immunizationContorller.getImmunizationInfo(students);
    vaccine = immunizationContorller.getList();
    
    TeacherController teacherController = new TeacherController();
    teachers = teacherController.getList();
    
    GroupController groupController = new GroupController(students,teachers);
    Map<Integer,List<Group>> groups = groupController.getGroups();
    ClassRoomController classRoomController = new ClassRoomController(groups);
    classrooms = classRoomController.getList();
    
//        System.out.println(vaccine);
    //this.immuMap=immuMap;
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        splitViewMenuScrollPanel = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnManageStudent = new javax.swing.JButton();
        btnManageTeacher = new javax.swing.JButton();
        btnManageClassroom = new javax.swing.JButton();
        btnManageImmunition = new javax.swing.JButton();
        btnManageAlert = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPanel.setDividerLocation(230);
        splitPanel.setDividerSize(10);
        splitPanel.setName(""); // NOI18N

        splitViewMenuScrollPanel.setBackground(new java.awt.Color(102, 102, 102));
        splitViewMenuScrollPanel.setMinimumSize(new java.awt.Dimension(200, 23));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnManageStudent.setText("Manage Student Area");
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });

        btnManageTeacher.setText("Manage Teacher Area");
        btnManageTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTeacherActionPerformed(evt);
            }
        });

        btnManageClassroom.setText("Manage Classroom Area");
        btnManageClassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageClassroomActionPerformed(evt);
            }
        });

        btnManageImmunition.setText("Manage Immunition Area");
        btnManageImmunition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageImmunitionActionPerformed(evt);
            }
        });

        btnManageAlert.setText("Manage Alert Area");
        btnManageAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAlertActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnLogin.setText("Sign in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageImmunition, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnManageClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnManageTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnManageAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 582, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageAlert, btnManageClassroom, btnManageImmunition, btnManageStudent, btnManageTeacher});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnManageStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageClassroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageImmunition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(77, 77, 77))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogin, btnManageAlert, btnManageClassroom, btnManageImmunition, btnManageStudent, btnManageTeacher});

        splitViewMenuScrollPanel.setViewportView(jPanel1);

        splitPanel.setLeftComponent(splitViewMenuScrollPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPanel.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
        // TODO add your handling code here:
        StudentsShowAllJPanel studentsShowAllJPanel = new StudentsShowAllJPanel(userProcessContainer, students);
        userProcessContainer.add("studentsShowAllJPanel", studentsShowAllJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStudentActionPerformed

    private void btnManageTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTeacherActionPerformed
        // TODO add your handling code here:
        TeachersShowAllJPanel teachersShowAllJPanel = new TeachersShowAllJPanel(userProcessContainer,teachers);
        userProcessContainer.add("teachersShowAllJPanel", teachersShowAllJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageTeacherActionPerformed

    private void btnManageClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageClassroomActionPerformed
        // TODO add your handling code here:
        ClassroomsShowAllJPanel classroomsShowAllJPanel = new ClassroomsShowAllJPanel(userProcessContainer,classrooms);
        userProcessContainer.add("classroomsShowAllJPanel", classroomsShowAllJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageClassroomActionPerformed

    private void btnManageImmunitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageImmunitionActionPerformed
        // TODO add your handling code here:


        ManageImmunitionRecordJPanel manageImmunitionRecordJPanel = new ManageImmunitionRecordJPanel( userProcessContainer, immunizationContorller,students);

        userProcessContainer.add("manageImmunitionRecordJPanel", manageImmunitionRecordJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageImmunitionActionPerformed

    private void btnManageAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAlertActionPerformed
        // TODO add your handling code here:
        AlertJPanel alertJPanel = new AlertJPanel(userProcessContainer);
        userProcessContainer.add("alertJPanel", alertJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAlertActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        LoginAreaJPanel loginAreaJPanel = new LoginAreaJPanel(userProcessContainer);
        userProcessContainer.add("loginAreaJPanel", loginAreaJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnManageAlert;
    private javax.swing.JButton btnManageClassroom;
    private javax.swing.JButton btnManageImmunition;
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JButton btnManageTeacher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane splitPanel;
    public javax.swing.JScrollPane splitViewMenuScrollPanel;
    public javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
