/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ke
 */
public class ApplicationMainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationMainJFrame
     */
   
     private JPanel userProcessContainer;
    public ApplicationMainJFrame() {
        initComponents();
        this.userProcessContainer=userProcessContainer;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        splitViewMenuScrollPanel = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnManageStudent = new javax.swing.JButton();
        btnManageTeacher = new javax.swing.JButton();
        btnManageClassroom = new javax.swing.JButton();
        btnManageImmunition = new javax.swing.JButton();
        btnManageAlert = new javax.swing.JButton();
        userProcessContainerJPanel = new javax.swing.JPanel();
        placeholderLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        loginMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPanel.setDividerLocation(230);
        splitPanel.setDividerSize(10);
        splitPanel.setName(""); // NOI18N

        splitViewMenuScrollPanel.setMinimumSize(new java.awt.Dimension(200, 23));

        btnManageStudent.setText("Manage Student Area");
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });

        btnManageTeacher.setText("Manage Teacher Area");
        btnManageTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTeacherActionPerformed(evt);
            }
        });

        btnManageClassroom.setText("Manage Classroom Area");
        btnManageClassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageClassroomActionPerformed(evt);
            }
        });

        btnManageImmunition.setText("Manage Immunition Area");
        btnManageImmunition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageImmunitionActionPerformed(evt);
            }
        });

        btnManageAlert.setText("Manage Alert Area");
        btnManageAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAlertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageImmunition, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnManageClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnManageTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnManageStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(569, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageAlert, btnManageClassroom, btnManageImmunition, btnManageStudent, btnManageTeacher});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(btnManageStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageClassroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageImmunition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageAlert, btnManageClassroom, btnManageImmunition, btnManageStudent, btnManageTeacher});

        splitViewMenuScrollPanel.setViewportView(jPanel1);

        splitPanel.setLeftComponent(splitViewMenuScrollPanel);

        userProcessContainerJPanel.setLayout(new java.awt.BorderLayout());

        placeholderLabel.setForeground(new java.awt.Color(102, 102, 102));
        placeholderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placeholderLabel.setText("Select a panel from the left");
        placeholderLabel.setAlignmentX(0.5F);
        userProcessContainerJPanel.add(placeholderLabel, java.awt.BorderLayout.CENTER);

        splitPanel.setRightComponent(userProcessContainerJPanel);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        loginMenu.setMnemonic('h');
        loginMenu.setText("Login");
        loginMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        loginMenuItem.setMnemonic('t');
        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(loginMenuItem);

        logoutMenuItem.setMnemonic('t');
        logoutMenuItem.setText("Logout");
        loginMenu.add(logoutMenuItem);

        menuBar.add(loginMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        // TODO add your handling code here:
        LoginJPanel loginJPanel = new LoginJPanel(userProcessContainer);
        userProcessContainer.add("loginJPanel", loginJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);    
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
        // TODO add your handling code here:
        StudentsShowAllJPanel studentsShowAllJPanel = new StudentsShowAllJPanel(userProcessContainer);
        userProcessContainer.add("studentsShowAllJPanel", studentsShowAllJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStudentActionPerformed

    private void btnManageTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTeacherActionPerformed
        // TODO add your handling code here:
        TeachersShowAllJPanel teachersShowAllJPanel = new TeachersShowAllJPanel(userProcessContainer);
        userProcessContainer.add("teachersShowAllJPanel", teachersShowAllJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageTeacherActionPerformed

    private void btnManageClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageClassroomActionPerformed
        // TODO add your handling code here:
        ClassroomsShowAllJPanel classroomsShowAllJPanel = new ClassroomsShowAllJPanel(userProcessContainer);
        userProcessContainer.add("classroomsShowAllJPanel", classroomsShowAllJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageClassroomActionPerformed

    private void btnManageImmunitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageImmunitionActionPerformed
        // TODO add your handling code here:
        ManageImmunitionRecordJPanel manageImmunitionRecordJPanel = new ManageImmunitionRecordJPanel(userProcessContainer);
        userProcessContainer.add("manageImmunitionRecordJPanel", manageImmunitionRecordJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageImmunitionActionPerformed

    private void btnManageAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAlertActionPerformed
        // TODO add your handling code here:
        AlertJPanel alertJPanel = new AlertJPanel(userProcessContainer);
        userProcessContainer.add("alertJPanel", alertJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAlertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAlert;
    private javax.swing.JButton btnManageClassroom;
    private javax.swing.JButton btnManageImmunition;
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JButton btnManageTeacher;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu loginMenu;
    public javax.swing.JMenuItem loginMenuItem;
    public javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JLabel placeholderLabel;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JSplitPane splitPanel;
    public javax.swing.JScrollPane splitViewMenuScrollPanel;
    public javax.swing.JPanel userProcessContainerJPanel;
    // End of variables declaration//GEN-END:variables
}
